print("ingresa tu nombre=>")
nombre= input()
print("ingresa tu apellido=>")
apellido= input()
print("ingresa tu edad=>")
edad= input()
print("ingresa tu discapacidad=>")
discapacidad=input()
print("ingresa tu lesion=>")
lesion= input()
print("coloque su nacionalidad=>")
nacionalidad=input()
print(" hola soy"+nombre+""+apellido+" ,tengo"+edad+" anos, tengo"  +discapacidad+" y sufro de" +lesion+" y soy de "+nacionalidad+".")
